build: off
version: '{build}'
environment:
  matrix:
    - nodejs_version: '8'
    - nodejs_version: '6'
    - nodejs_version: '4'
platform:
  - x86
  - x64
cache:
  - node_modules
install:
  - ps: Install-Product node $env:nodejs_version
  - npm i -g npx
  - npm install
test_script:
  - node --version
  - npm --version
  - npx --version
  - npm test
after_test:
- npx codecov
